# Generated by Django 4.0.3 on 2022-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tilte',
            field=models.CharField(default='', max_length=50),
        ),
    ]
